### ISSUE TITLE
Issue with source locations in clasp

### ISSUE THREAD

**Issue by kpoeck** [Shinmera/definitions#3]
Hello,
the following code throws an error, since ext:source-location returns a list of locations and transform-source-location expects a single location and ext:source-location-pathname errors on a list

As a workaround I can easily take the car of the list, but I don't know if this is the correct way to handle this.

```lisp
(defmacro define-definition-source-location-type (class type)
  `(defmethod source-location ((,class ,class))
     (transform-source-location
      (ext:source-location (designator ,class) ,type))))

(define-definition-source-location-type function :function)
(define-definition-source-location-type generic-function :function)
(defun transform-source-location (source-location)
  (when source-location
    (list :file (ext:source-location-pathname source-location)
          :offset (ext:source-location-offset source-location))))
````

**Comment by Shinmera** [comment]
@Bike Can you advise?

**Comment by kpoeck** [comment]
This is more a question of what should be done in definition should there be multiple source locations.
This code makes the problem go away by discarding further locations, but might or might not what you want:
```lisp
(defun transform-source-location (source-location)
  (when source-location
    (when (listp source-location)
      (setq source-location (first source-location)))
    (list :file (ext:source-location-pathname source-location)
          :offset (ext:source-location-offset source-location))))
````

**Comment by Shinmera** [comment]
I don't know what it means for something to have multiple source locations. It makes no sense to me.

**Comment by kpoeck** [comment]
Well in sbcl.lisp there is
```lisp
(defmacro define-definition-introspect-type (class type)
  `(defmethod source-location ((,class ,class))
     (transform-definition-source
      (first (sb-introspect:find-definition-sources-by-name (designator ,class) ,type)))))
`````

Isn't that the same problem? will go for first.

In slime, I often have multiple-source-locations to choose from, when I do meta-dot, at least in generic-functions this seems obvious, for functions that were being redefined I believe I get the same
